---

  - name: install python pip
    become: yes
    apt:
      name:
        - python3-dev
        - python3-pip
      state: latest

  - name: install aws cli client and boto3
    become: yes
    pip: 
      name: 
        - awscli
        - boto3
      state: latest

  - name: ensure aws configuration directory
    become: yes
    file:
      path: "/home/{{ item.key }}/.aws"
      state: directory
      owner: "{{ item.key }}"
      group: "{{ item.key }}"
    when: item.value.aws is defined
    loop: "{{ lookup('dict', dev_workstation.workspaces, wantlist=True) }}"

  - name: configure aws
    become: yes
    template:
      dest: "/home/{{ item.key }}/.aws/config"
      src: "aws/config.j2"
      owner: "{{ item.key }}"
      group: "{{ item.key }}"
      backup: yes
    when: item.value.aws is defined
    loop: "{{ lookup('dict', dev_workstation.workspaces, wantlist=True) }}"

  - name: configure aws credentials
    become: yes
    template:
      dest: "/home/{{ item.key }}/.aws/credentials"
      src: "aws/credentials.j2"
      owner: "{{ item.key }}"
      group: "{{ item.key }}"
      mode: "0600" # keep credentials secret!
      backup: yes
    when: item.value.aws is defined
    loop: "{{ lookup('dict', dev_workstation.workspaces, wantlist=True) }}"

  - name: configure aws cli command completion
    become: yes
    become_user: "{{ item.key }}"
    blockinfile:
      dest: "/home/{{ item.key }}/.bashrc"
      marker: "# {mark} ANSIBLE MANAGED BLOCK - AWS"
      content: |
        complete -C '/usr/local/bin/aws_completer' aws
    when: item.value.aws is defined
    loop: "{{ lookup('dict', dev_workstation.workspaces, wantlist=True) }}"