---

  - name: install python pip
    become: yes
    apt:
      name:
        - python3-dev
        - python3-pip
      state: latest

  - name: install boto3
    become: yes
    pip: 
      name: 
        - boto3
      state: latest
  
  - name: remove old version of aws cli from pip
    become: yes
    pip:
      name:
        - awscli
      state: absent

  - name: remove old version of aws cli from apt
    become: yes
    apt: 
      name: awscli
      state: absent

  - name: download awscli bundled installer
    unarchive:
      src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      dest: /tmp
      copy: no
      creates: /tmp/aws

  - name: run awscli installer
    become: yes
    command: /tmp/aws/install
    args:
      creates: /usr/local/aws-cli

  - name: add symlink
    become: yes
    file: state=link src=/usr/local/bin/aws dest=/usr/bin/aws

  - name: get awscli version
    shell: "aws --version"
    register: aws_version
    changed_when: false

  - name: log installed awscli version
    debug: var=aws_version.stdout
  
  - name: ensure aws configuration directory
    become: yes
    file:
      path: "/home/{{ item.key }}/.aws"
      state: directory
      owner: "{{ item.key }}"
      group: "{{ item.key }}"
    when: item.value.aws is defined
    loop: "{{ lookup('dict', dev_workstation.workspaces, wantlist=True) }}"

  - name: configure aws
    become: yes
    template:
      dest: "/home/{{ item.key }}/.aws/config"
      src: "aws/config.j2"
      owner: "{{ item.key }}"
      group: "{{ item.key }}"
      backup: yes
    when: item.value.aws is defined
    loop: "{{ lookup('dict', dev_workstation.workspaces, wantlist=True) }}"

  - name: configure aws credentials
    become: yes
    template:
      dest: "/home/{{ item.key }}/.aws/credentials"
      src: "aws/credentials.j2"
      owner: "{{ item.key }}"
      group: "{{ item.key }}"
      mode: "0600" # keep credentials secret!
      backup: yes
    when: item.value.aws is defined
    loop: "{{ lookup('dict', dev_workstation.workspaces, wantlist=True) }}"

  - name: configure aws cli command completion
    become: yes
    become_user: "{{ item.key }}"
    blockinfile:
      dest: "/home/{{ item.key }}/.bashrc"
      marker: "# {mark} ANSIBLE MANAGED BLOCK - AWS"
      content: |
        complete -C '/usr/local/bin/aws_completer' aws
    when: item.value.aws is defined
    loop: "{{ lookup('dict', dev_workstation.workspaces, wantlist=True) }}"