---

  - name: install aws cli client
    become: yes
    apt: 
      name: awscli
      state: latest

  - name: ensure aws configuration directory
    become: yes
    file:
      path: "/home/{{ item.key }}/.aws"
      state: directory
      owner: "{{ item.key }}"
      group: "{{ item.key }}"
    when: item.value.aws is defined
    loop: "{{ lookup('dict', dev_workstation.workspaces, wantlist=True) }}"

  - name: configure aws
    become: yes
    template:
      dest: "/home/{{ item.key }}/.aws/config"
      src: "aws/config.j2"
      owner: "{{ item.key }}"
      group: "{{ item.key }}"
    when: item.value.aws is defined
    loop: "{{ lookup('dict', dev_workstation.workspaces, wantlist=True) }}"

  - name: configure aws credentials
    become: yes
    template:
      dest: "/home/{{ item.key }}/.aws/credentials"
      src: "aws/credentials.j2"
      owner: "{{ item.key }}"
      group: "{{ item.key }}"
      mode: "0600" # keep credentials secret!
    when: item.value.aws is defined
    loop: "{{ lookup('dict', dev_workstation.workspaces, wantlist=True) }}"
