---
# https://gradle.org/install/
- name: install gradle - create path
  become: yes
  file:
    path: /opt/gradle
    state: directory
  when: dev_workstation.gradle is defined and dev_workstation.gradle == True

- name: install gradle - download
  become: yes
  unarchive:
    src: "{{gradle_url}}"
    dest: /opt/gradle
    remote_src: yes
  when: dev_workstation.gradle is defined and dev_workstation.gradle == True

- name: install gradle - smylink binary
  become: yes
  file:
    path: /usr/local/bin/gradle
    src: "/opt/gradle/gradle-{{gradle_version}}/bin/gradle"
    state: link
  when: dev_workstation.gradle is defined and dev_workstation.gradle == True

- name: ensure gradle configuration directory
  become: yes
  file:
    path: "/home/{{ item.key }}/.gradle"
    state: directory
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
  when: item.value.gradle.properties is defined
  loop: "{{ lookup('dict', dev_workstation.workspaces, wantlist=True) }}"

- name: configure gradle
  become: yes
  template:
    dest: "/home/{{ item.key }}/.gradle/gradle.properties"
    src: "gradle/gradle.properties.j2"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    backup: yes
  when: item.value.gradle.properties is defined
  loop: "{{ lookup('dict', dev_workstation.workspaces, wantlist=True) }}"