---

 - name: install amazon repro
   include_tasks:
    file: "java_amazon_corretto_repository.yml"

 - name: install amazon corretto 11
   become: yes
   apt: 
    name: java-11-amazon-corretto-jdk
    state: latest
    force: yes

 - name: set JAVA_HOME
   become: yes
   lineinfile: 
    dest: "/etc/environment"
    state: present
    regexp: "^JAVA_HOME"
    line: "JAVA_HOME=/usr/lib/jvm/java-11-amazon-corretto"