---

 - name: add key for amazon corretto repository
   become: yes
   apt_key: 
    url: "https://apt.corretto.aws/corretto.key"
    state: present

 - name: add amazon corretto repository
   become: yes
   apt_repository: 
    repo: "deb https://apt.corretto.aws stable main"
    state: "present"
    filename: "amazon_corretto" 
    update_cache: "yes"