---

 - name: install amazon repro
   include_tasks:
    file: "java_amazon_corretto_repository.yml"

 - name: install amazon corretto
   become: yes
   apt: 
    name: "java-{{dev_workstation.java.jdk}}-amazon-corretto-jdk"
    state: latest
    force: yes

 - name: set JAVA_HOME
   become: yes
   lineinfile: 
    dest: "/etc/environment"
    state: present
    regexp: "^JAVA_HOME"
    line: "JAVA_HOME=/usr/lib/jvm/java-{{dev_workstation.java.jdk}}-amazon-corretto"