---
- name: install and configure git
  include_tasks: "git.yml"
  when: dev_workstation.git

- name: install ansible
  include_tasks: "ansible.yml"
  when: dev_workstation.ansible

- name: install and configure aws cli
  include_tasks: "aws.yml"
  when: dev_workstation.aws