---
- name: install and configure git
  include_tasks:
    file: "git.yml"
    apply:
      tags: "git"
  when: dev_workstation.git is defined and dev_workstation.git == True
  tags: "git"

- name: install ansible
  include_tasks:
    file: "ansible.yml"
    apply:
      tags: "ansible"
  when: dev_workstation.ansible is defined and dev_workstation.ansible == True
  tags: "ansible"

- name: install and configure aws cli
  include_tasks:
    file: "aws.yml"
    apply:
      tags: "aws"
  when: dev_workstation.aws is defined and dev_workstation.aws == True
  tags: "aws"

- name: install and configure python
  include_tasks:
    file: "python.yml"
    apply:
      tags: "python"
  when: dev_workstation.python is defined and dev_workstation.python == True
  tags: "python"

- name: install docker
  include_tasks:
    file: "docker.yml"
    apply:
      tags: "docker"
  when: dev_workstation.docker is defined and dev_workstation.docker == True
  tags: "docker"

- name: install java
  include_tasks:
    file: "java.yml"
    apply:
      tags: "java"
  when: dev_workstation.java is defined
  tags: "java"

- name: install eclipse_cdt
  include_tasks:
    file: "eclipse_cdt.yml"
    apply:
      tags: "eclipse_cdt"
  when: dev_workstation.eclipse_cdt is defined and dev_workstation.eclipse_cdt == True
  tags: "eclipse_cdt"

- name: install node version manager and node lts
  include_tasks:
    file: "nodejs.yml"
    apply:
      tags: "nodejs"
  vars:
    - user: "{{ workspace.key }}"
  loop: "{{ lookup('dict', dev_workstation.workspaces, wantlist=True) }}"
  loop_control:
    loop_var: "workspace"
  when: dev_workstation.nodejs is defined and dev_workstation.nodejs == True
  tags: "nodejs"

- name: install tools
  include_tasks:
    file: "tools.yml"
    apply:
      tags: "tools"
  when: dev_workstation.tools is defined
  tags: "tools"