---
 - name: ensure bin folder
   become: yes
   become_user: "{{ user }}"
   file: path="~/bin/" state=directory mode="0755"

 - name: download nvm manager install script
   become: yes
   become_user: "{{ user }}"
   get_url: url="https://raw.githubusercontent.com/nvm-sh/nvm/{{nvm_version}}/install.sh" dest="~/bin/install_nvm.sh" mode="0740"
   register: get_install_script

 - name: install nvm manager for current user
   become: yes
   become_user: "{{ user }}"
   when: get_install_script.changed
   shell: "~/bin/install_nvm.sh"
   args:
     executable: /bin/bash

 - name: install node LTS using nvm manager
   become: yes
   become_user: "{{ user }}"
   when: get_install_script.changed
   shell: "source ~/.nvm/nvm.sh && nvm install --lts"
   args:
     executable: /bin/bash
   register: nvm_install_result
   changed_when: "'is already installed.' not in nvm_install_result.stdout and 'is already installed.' not in nvm_install_result.stderr"
